name: chatinteractivo
description: "Chatbot basado en chatGPT"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  connectivity_plus: ^4.0.1
  google_generative_ai: ^0.1.0  # Movido a dependencies
  intl: ^0.17.0  # Movido a dependencies
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.1.1
  speech_to_text: ^7.0.0
  flutter_tts: ^3.6.0
  permission_handler: ^11.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg